storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@alephscript/*":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "node-red-contrib-alephscript-*":
    access: $all
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
